DROP DATABASE IF EXISTS bingeDB;
CREATE DATABASE bingeDB;

USE bingeDB;



CREATE TABLE items(
 id INT NOT NULL AUTO_INCREMENT,
 movie_name VARCHAR(50),
 movie_year INT NOT NULL,
 movie_streaming VARCHAR(20),
 PRIMARY KEY (id)
);


LOAD DATA INFILE 'movieSheet.csv'
INTO TABLE items
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
